apiVersion: apps/v1
kind: Deployment
metadata:
 name: kitsune
spec:
 replicas: 3
 selector:
   matchLabels:
     app: kitsune
 template:
   metadata:
     labels:
       app: kitsune
   spec:
     containers:
     - name: kitsune
       image: pathespe/kitsune
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 3000
